# Proposal

## Research Topic

Since the beginning of the pandemic, scientists over the world has been striving to develop vaccines to stop, or at least, slow down the spread of COVID-19. The vaccines are claimed to be effective in decreasing the severe case, hospitalization rate, and fatality rate by CDC.[1] However, there exists doubts on the effectiveness and safety of vaccines. Especially for children, the aged, and other groups with low immunity, whether vaccines bringing more benefits than harm is disputed. Furthermore, as the variants of the virus appear continuously, boosters targeted at the new variants come out subsequently. We might also curious about if people gradually lose the interests and trust in these new boosters. The opinion regarding these questions and the choice of getting COVID-19 vaccines might be influenced by multifarious factors, such as government policies, ages, races, and genders.

In this project, we will focus on NYC, where the disease once breakout and caused huge loss to economics and public health. In NYC, there is requirement for employees who work in person or interact with public to be fully vaccinated until this November.[2] We are going to investigate the attitudes and choices of citizens in NYC towards COVID-19 vaccines through the status of vaccinations by different groups. To be specific, we are interested in whether people with certain characteristics are more likely to get vaccinated than other groups.

[1] <https://www.cdc.gov/coronavirus/2019-ncov/vaccines/vaccine-benefits.html>

[2] <https://www1.nyc.gov/site/doh/COVID/COVID-19-vaccine-workplace-requirement.page>

## Data availability

In order to analyze the NYC citizens' attitudes towards the COVID-19 vaccination, we plan to collect data on the NYC citizens' COVID-19 vaccination status from the [NYC-health](https://www1.nyc.gov/site/doh/covid/covid-19-data-vaccines.page) website. The data how vaccinations in NYC have progressed since December 2020 and will be updated once a week on Thursdays.

The [data](https://github.com/nychealth/COVID-vaccine-data) can be divided into two categories: `doses` and `people`

### doses/

The `doses` folder denotes the daily and cumulative **administered doses number** of the COVID-19 vaccine in NYC.

-   *Doses Administered:* The number of COVID-19 vaccine doses that have been administered in NYC and reported to the CIR. This includes doses administered to residents and non-residents of all ages.
-   *Doses Number:* Daily and cumulative information of vaccination. Data is divided into the two-dose, the one dose and booster.
    -   *Dose 1 of 2:* First dose administered of a two-dose primary vaccine series (Pfizer-BioNTech and Moderna)
    -   *Dose 2 of 2:* Second dose administered of a two-dose primary vaccine series (Pfizer-BioNTech and Moderna)
    -   *Single dose:* The dose administered of a single-dose primary vaccine series (Johnson & Johnson)
    -   *Additional/Booster 1:* First booster doses administered after the primary COVID-19 vaccine series.
    -   *Additional/Booster 2:* Second booster doses administered after the primary COVID-19 vaccine series and one booster dose.

There are some descriptions about the primary data and its format.

| Variable Name         | Description                                                                                                                    | Data Type  |
|-----------------------|--------------------------------------------------------------------------------------------------------------------------------|------------|
| DATE                  | Date                                                                                                                           |            |
| RESIDENCY             | Residency status (NYC; outside of NYC; unknown)                                                                                |            |
| DOSE1_CUMULATIVE      | Cumulative number of first doses administered of a two-dose COVID-19 vaccine series (Dose 1 of 2)                              | Cumulative |
| DOSE2_CUMULATIVE      | Cumulative number of second doses administered of a two-dose COVID-19 vaccine series (Dose 2 of 2)                             | Cumulative |
| SINGLE_CUMULATIVE     | Cumulative number of doses administered of a single-dose COVID-19 vaccine (Single dose)                                        | Cumulative |
| ADDITIONAL_CUMULATIVE | Cumulative number of additional doses administered                                                                             | Cumulative |
| ALLDOSES_CUMULATIVE   | Cumulative number of COVID-19 vaccine doses delivered or administered (Dose 1 of 2; Dose 2 of 2; Single dose; Additional dose) | Cumulative |

### People/

The `people` folder contains information on the number of NYC residents vaccinated for COVID-19 in NYC, NYS, NJ or elsewhere and reported to the CIR by NYC providers.

These data shows how many NYC residents have been vaccinated by **borough, age, race/ethnicity and sex**, and the cumulative administered doses numbers in NYC.

Vaccination status is classified into the following categories:

-   *Partially Vaccinated*: People who have received the first dose of a two-dose primary vaccine series.
-   *Completed primary series/Fully vaccinated*: People who have received the two-dose series or the single-dose series.
-   *At least one dose*: People who have received either the first dose of the two-dose or the single-dose, which includes people who are both partially and fully vaccinated. Therefore, it can't be summed when doing statistic.
-   *Additional/booster doses*: People who have received additional doses of an FDA-approved vaccine after completing their primary series. This includes first and second booster shots.

*Population estimates:* The number of people vaccinated may exceed the estimated population and lead to more than 100% vaccination coverage, especially for smaller demographic categories and geographies. Population counts were calculated using estimates updated on October 9, 2020 to reflect annual population estimates for all NYC citizens. These estimates do not represent the 2020 Census or recent changes to NYC's population as a result of in-migration or out-migration.

*Age groups:* Data are reported for the following age groups: 5-12, 13-17, 18-24, 25-34, 35-44, 45-54, 55-64, 65-74, 75-84, and 85+ years. Among people under 18, only those aged 5 to 17 years are currently eligible for COVID-19 vaccination.

There are some descriptions about the primary data and its format.

| Variable Name               | Description                                                                                                              | Data Type  |
|-----------------------------|--------------------------------------------------------------------------------------------------------------------------|------------|
| DATE                        | Date last updated                                                                                                        |            |
| NEIGHBORHOOD_NAME           | Neighborhood name of the MODZCTA                                                                                         |            |
| BOROUGH                     | Name of borough                                                                                                          |            |
| MODZCTA                     | Modified ZCTA (Zip Code Tabulation Area, which solidifies Zip codes into units of area)                                  |            |
| Label                       | List of the ZIP Code Tabulation Areas (ZCTAs) that are bundled into the MODZCTA                                          |            |
| RACE_ETHNICITY              | Race/ethnicity group                                                                                                     |            |
| AGE_GROUP                   | Age in years                                                                                                             |            |
| POP_DENOMINATOR             | Population denominators derived from intercensal estimates as of 2019. Please see the technical notes for a description. |            |
| COUNT_PARTIALLY_CUMULATIVE  | Number of people partially vaccinated by MODZCTA                                                                         | Cumulative |
| COUNT_FULLY_CUMULATIVE      | Number of people who completed the primary series by MODZCTA                                                             | Cumulative |
| COUNT_1PLUS_CUMULATIVE      | Number of people who have received at least one dose of COVID_19 vaccine by MODZCTA                                      | Cumulative |
| COUNT_ADDITIONAL_CUMULATIVE | Number of people with additional/booster doses by MODZCTA                                                                | Cumulative |
| PERC_PARTIALLY              | Estimated percentage of the total population partially vaccinated by MODZCTA                                             | Cumulative |
| PERC_FULLY                  | Estimated percentage of the population who completed the primary series by MODZCTA                                       | Cumulative |
| PERC_1PLUS                  | Estimated percentage of the population who have received at least one dose of COVID-19 vaccine by MODZCTA                | Cumulative |
| PERC_ADDIITONAL             | Estimated percentage of the population with additinonal/booster doses by MODZCTA                                         | Cumulative |
